apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: crapi-2
  name: waitfor-grant
subjects:
- kind: ServiceAccount
  name: default
  namespace: crapi-2
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: waitfor-reader
  apiGroup: ""
