apiVersion: apps/v1
kind: Deployment
metadata:
  name: crapi-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crapi-web
  template:
    metadata:
      labels:
        app: crapi-web
    spec:
      containers:
      - name: crapi-web
        image: crapi/crapi-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: crapi-web-configmap